# Generated by Django 5.0.4 on 2025-07-07 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.TextField(default=1, max_length=1500, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(1500)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
