# Generated by Django 5.0.4 on 2025-07-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content_post_description_post_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
