# Generated by Django 5.0.4 on 2025-07-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_meta_description_remove_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='note',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
